### ISSUE TITLE
Do you have an helper function for placing a plane on a line?

### ISSUE THREAD

**Issue by tsukasa1989** [tdhooper/threejs-slice-geometry#13]
Hi,

My customer can draw lines to split the geometry. So I have 2 points where I want to put the plane on and then slice the geometry.

Do you have helper function to put a plane on the line?

Thank you,

Niels den Otter

**Comment by tdhooper** [comment]
You need at least three points to create a plane:

https://threejs.org/docs/#api/en/math/Plane.setFromCoplanarPoints

You could use your camera position as the third point. That would work if your client is drawing a line on the screen from the camera’s viewpoint.

**Comment by tsukasa1989** [comment]
Thank you very much, didn't know this function existed!
