### ISSUE TITLE
BufferGeometry support

### ISSUE THREAD

**Issue by makc** [tdhooper/threejs-slice-geometry#2]
as they say they are going to eventually drop Geometry. there is still quite some time before they do, but...

**Comment by tdhooper** [comment]
I think it makes more sense to make this tool library agnostic, with helpers for Three's geometry types. For now the manual BufferGeometry -> Geometry and back again workflow isn't awful.

**Comment by makc** [comment]
Closing then.
> BufferGeometry -> Geometry and back again

Just left the code in #7

**Comment by tdhooper** [comment]
Thank you.
