### ISSUE TITLE
Use with BufferGeometry

### ISSUE THREAD

**Issue by fiSCIENCES** [tdhooper/threejs-slice-geometry#7]
Is it possible to use a bufferGeometry instead of a simple Geometry? I need to cut them with a planeGeometry and both are in 3D space coordinates (Mesh).

My complexe bufferGemotry came from ObjectLoader().

Or how can we handle this?

Thank you.

**Comment by fiSCIENCES** [comment]
By the way, I'M willing to pay for this feature. Or for another solution.

**Comment by makc** [comment]
you can convert to Geometry, then cut, then convert back )

**Comment by makc** [comment]
in any case it is not possible to do in-place (since one triangle can leave two after being cut), so you will need to create 2nd buffer geometry with any other code.

**Comment by fiSCIENCES** [comment]
I need someone to help me with this. Can you handle it? For what cost? Thank you.

**Comment by makc** [comment]
@fiSCIENCES sorry I never saw your comment until now. In unlikely case you still need that, I was referring to this:
```javascript
var geometry = new THREE.Geometry;
geometry.fromBufferGeometry (bufferGeometry);
// ^^^ you can now cut geometry and use the result 'as is', or convert back to buffer geometry:
var bufferGeometry2 = new THREE.BufferGeometry;
bufferGeometry2.fromGeometry (geometry);
```
